services:
  gym-scraper:
    build: .
    container_name: uzimtumas-scraper
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"